apiVersion: user.enmasse.io/v1alpha1
kind: MessagingUser
metadata:
  name: results.readuser
spec:
  username: readuser
  authentication:
    type: password
    password: aGFja2Zlc3Q= # Base64 encoded hackfest
  authorization:
     - addresses: ["result*"]
       operations: ["recv"]

