# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
    
# Camel Spring Boot
camel:
  springboot:
    name: InputProducer

# AMQPHub
amqphub:
  amqp10jms:
    pool:
      enabled: true
    remote-url: amqps://localhost:5672
    #username: amqpuser
    #password: password

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache.camel: DEBUG
    org.apache.camel.examples: DEBUG

# AMQP
amqp:
  timer-period: 1000
  min-message-size: 1
  max-message-size: 1024
  client-id: client1
  producer-queue: inputonline
  ssl-truststore-path: /tmp/client.ts
  ssl-truststore-password: r3dh4t1!
  ssl-cert-alias: broker