apiVersion: admin.enmasse.io/v1alpha1
kind: AddressSpacePlan
metadata:
  name: online-plan
  labels:
    app: enmasse
  annotations:
    enmasse.io/defined-by: infraconfig-standard
displayName: Online Plan
displayOrder: 0
shortDescription: A plan for Online
longDescription:A plan for Online address space
addressSpaceType: standard
addressPlans:
- online-queue
resources:
- name: router
  max: 2.0
- name: broker
  max: 2.0
- name: aggregate
  max: 4.0