apiVersion: admin.enmasse.io/v1alpha1
kind: AddressSpacePlan
metadata:
  name: batch-plan
  labels:
    app: enmasse
  annotations:
    enmasse.io/defined-by: infraconfig-batch
displayName: Online Batch Plan
displayOrder: 0
shortDescription: A plan for Batch 
longDescription: A plan for Batch address space
addressSpaceType: standard
addressPlans:
- batch-queue
resources:
- name: router
  max: 2.0
- name: broker
  max: 2.0
- name: aggregate
  max: 4.0