apiVersion: admin.enmasse.io/v1beta1
kind: AddressPlan
metadata:
  name: online-queue
  labels:
    app: enmasse
displayName: Online Queue
displayOrder: 0
shortDescription: Creates the Online queue for input_online.
longDescription: Creates the Online queue for input_online.
addressType: queue
requiredResources:
- name: router
  credit: 0.001
- name: broker
  credit: 0.01