apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: infraconfig-alert
  labels:
    app: enmasse
spec:
  version: 0.26-SNAPSHOT
  admin:
    resources:
      memory: 512Mi
  router:
    minReplicas: 1
    resources:
      memory: 512Mi
    linkCapacity: 250