apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: prod-high-priority 
value: 1000000 
globalDefault: false 
description: "This priority class should be used for PROD Messaging service infra and applications only."