apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: infraconfig-batch
  labels:
    app: enmasse
spec:
  version: 0.26-SNAPSHOT
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 1Gi
      storage: 3Gi
    addressFullPolicy: FAIL
  router:
    minReplicas: 2
    resources:
      memory: 512Mi
    linkCapacity: 250