apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: infraconfig-alert
  labels:
    app: enmasse
spec:
  version: 0.26-SNAPSHOT
  admin:
    resources:
      memory: 512Mi
  router:
    minReplicas: 2
    resources:
      memory: 512Mi
    linkCapacity: 250
  broker:
    resources:
      memory: 0Mi
      storage: 0Gi
    addressFullPolicy: FAIL