apiVersion: user.enmasse.io/v1alpha1
kind: MessagingUser
metadata:
  name: eng-addressspace.client1
spec:
  username: client1
  authentication:
    type: password
    password: aGFja2Zlc3Q= # Base64 encoded hackfest
  authorization:
    - addresses: ["queue*"]
      operations: ["send","recv"]
