apiVersion: user.enmasse.io/v1alpha1
kind: MessagingUser
metadata:
  name: online.jmsClient
spec:
  username: jmsClient
  authentication:
    type: password
    password: aGFja2Zlc3Q= # Base64 encoded hackfest
  authorization:
    - addresses: ["input_online"]
      operations: ["recv"]
    - addresses: ["result_*"]
      operations: ["send"]

