apiVersion: user.enmasse.io/v1alpha1
kind: MessagingUser
metadata:
  name: alerts.writeuser
spec:
  username: writeuser
  authentication:
    type: password
    password: aGFja2Zlc3Q= # Base64 encoded hackfest
  authorization:
    - addresses: ["mytopic"]
      operations: ["send"]

